{{- include "yeti.workerDeployment" (dict
  "root" .
  "name" "tasks"
  "args" "[\"tasks\"]"
  "replicas" .Values.tasks.replicas
  "resources" .Values.tasks.resources
  "nodeSelector" .Values.tasks.nodeSelector
  "exports" .Values.exports.enabled
  "waitApi" true) }}
